# fly.toml app configuration file generated for ping-the-site on 2026-06-27T14:32:29Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ping-the-site'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
